[package]
name = "forza-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "forza"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
forza-config = { path = "../forza-config" }
forza-db = { path = "../forza-db" }
forza-gui = { path = "../forza-gui" }

[lints]
workspace = true
